# SN 2681
# Usage: Dyer Machine
substitutions:
  device_name: bw-shp6-2
  wifi_signal_max: "-40.0"
  current_res: "0.002358"
  voltage_div: "720.3"
  max_power: "3450"

esphome:
  name: ${device_name}
  on_boot:
    priority: -100
    then:
      if:
        condition:
          switch.is_off: relay
        then:
          output.turn_on: led

esp8266:
  board: esp8285
  restore_from_flash: false

wifi:
  domain: ".lan"
  output_power: 20
  reboot_timeout: 60min
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass
  networks:
    - ssid: !secret wifi_aux_ssid
      password: !secret wifi_aux_pass
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass

captive_portal:

logger:
  baud_rate: 0

api:
  reboot_timeout: 60min
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

binary_sensor:
  - platform: gpio
    id: button1
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

  - platform: template
    name: "${device_name} Dryer Running"
    id: machine_running
    icon: mdi:tumble-dryer
    device_class: running
    filters:
      - delayed_on: 30s
      - delayed_off: 30s
    lambda: |-
      if (isnan(id(hlw8012_power).state)) {
        return {};
      } else if (id(hlw8012_power).state > 100) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }

button:
  - platform: restart
    name: "${device_name} Restart"

output:
  - platform: gpio
    pin: GPIO0
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
    name: "${device_name} Relay"
    on_turn_on:
      then:
        - output.turn_off: led
    on_turn_off:
      then:
        - output.turn_on: led

status_led:
  pin:
    number: GPIO2
    inverted: true

sensor:
  - platform: uptime
    name: "${device_name} Uptime"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
    filters:
      - lambda: |-
          if (x <= ${wifi_signal_max}) {
            return x;
          } else {
            return {};
          }

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    voltage:
      id: hlw8012_voltage
      name: "${device_name} Voltage"
      unit_of_measurement: "V"
      icon: mdi:sine-wave
    power:
      id: hlw8012_power
      name: "${device_name} Power"
      unit_of_measurement: "W"
      icon: mdi:flash-outline
      on_value:
        - sensor.template.publish:
            id: hlw8012_current
            state: !lambda |-
              if (isnan(id(hlw8012_power).state) || isnan(id(hlw8012_voltage).state)) {
                return {};
              } else if (id(hlw8012_voltage).state > 0) {
                return id(hlw8012_power).state / id(hlw8012_voltage).state;
              } else {
                return {};
              }
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay
            - output.turn_on: led
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
    energy:
      id: hlw8012_energy
      name: "${device_name} Energy"
      unit_of_measurement: "Wh"
      icon: mdi:lightning-bolt
    change_mode_every: 4294967295
    update_interval: 10s

  - platform: template
    id: hlw8012_current
    name: "${device_name} Current"
    unit_of_measurement: "A"
    icon: mdi:flash-outline
    accuracy_decimals: 3
    update_interval: never

text_sensor:
  - platform: template
    name: "${device_name} Uptime Human Readable"
    id: uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Madrid"
    servers:
      - 192.168.1.1
      - hora.rediris.es
      - es.pool.ntp.org
