substitutions:
  device_name: bwshp6
  current_res: '0.00117'
  voltage_div: '755'
  max_power: '3450'

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  on_boot:
    then:
      - output.turn_off: led
      - switch.turn_on: relay

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: ".lan"
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass

captive_portal:

logger:
  baud_rate: 0

api:
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay
    name: '${device_name} Relay'
    on_turn_on:
      - output.turn_off: led
    on_turn_off:
      - output.turn_on: led

status_led:
  pin:
    number: GPIO02
    inverted: true

sensor:
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 300s

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO04
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: '${device_name} Current'
      unit_of_measurement: 'A'
      accuracy_decimals: 3
      icon: mdi:flash-outline
    voltage:
      name: '${device_name} Voltage'
      unit_of_measurement: 'V'
      icon: mdi:flash-outline
    power:
      name: '${device_name} Power'
      unit_of_measurement: 'W'
      icon: mdi:flash-outline
      id: hlw8012_power
      on_value_range:
        - above: ${max_power}
          then:
            - output.turn_on: led
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
    change_mode_every: 4
    update_interval: 10s

  - platform: total_daily_energy
    name: "${device_name} Energy"
    power_id: hlw8012_power
    unit_of_measurement: kWh
    accuracy_decimals: 5
    filters:
      - multiply: 0.001

time:
  - platform: homeassistant
    id: homeassistant_time
