substitutions:
  device_name: doorbell
  logger_baud_rate: "0"
  wifi_output_power: "20"
  wifi_signal_max: "-20.0"

esphome:
  name: ${device_name}
  platformio_options:
    board_build.f_cpu: 80000000L

esp8266:
  board: esp01_1m
  restore_from_flash: false

packages:
  common: !include .common.yaml

### Config ###

binary_sensor:
  - platform: gpio
    id: button1
    name: "${device_name} Button"
    pin:
      number: GPIO05
    filters:
      - delayed_on: 25ms
      - delayed_off: 3000ms
    on_press:
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
            - delay: 200ms
            - switch.turn_off: relay
            - delay: 600ms
            - switch.turn_on: relay
            - delay: 200ms
            - switch.turn_off: relay

globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'

switch:
  - platform: gpio
    name: "${device_name} Chime"
    pin: GPIO04
    id: relay
    icon: mdi:alarm-bell
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "${device_name} Chime Active"
    id: chime_active
    restore_mode: "DISABLED"
    icon: mdi:doorbell
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);
