substitutions:
  device_name: "esp-01s"

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m
  restore_from_flash: false

wifi:
  domain: ".lan"
  output_power: 20
  reboot_timeout: 60min
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass

captive_portal:

logger:
  baud_rate: 115200

api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

button:
  - platform: restart
    name: "${device_name} Restart"

status_led:
  pin:
    number: GPIO2
    inverted: true

sensor:
  - platform: uptime
    name: "${device_name} Uptime Timestamp"
    type: timestamp

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Madrid"
    servers:
      - 192.168.1.1
      - hora.rediris.es
      - es.pool.ntp.org
