substitutions:
  device_name: "esp-01s"

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m
  restore_from_flash: false

wifi:
  domain: ".lan"
  output_power: 20
  reboot_timeout: 60min
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass

captive_portal:

logger:
  baud_rate: 115200

api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

button:
  - platform: restart
    name: "${device_name} Restart"

status_led:
  pin:
    number: GPIO2
    inverted: true

sensor:
  - platform: uptime
    name: "${device_name} Uptime"
    type: seconds
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  - platform: uptime
    name: "${device_name} Uptime Timestamp"
    type: timestamp

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: template
    name: "${device_name} Uptime Human Readable"
    id: uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Madrid"
    servers:
      - 192.168.1.1
      - hora.rediris.es
      - es.pool.ntp.org
