substitutions:
  device_name: esp32-cam

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32cam

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: ".lan"
  ap:
    ssid: "ESP32-CAM"
    password: !secret wifi_ap_pass

captive_portal:

logger:
  baud_rate: 115200

api:
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: "${device_name} camera"
  resolution: UXGA

output:
  - platform: ledc
    pin: GPIO4
    channel: 2
    id: led

light:
  - platform: monochromatic
    output: led
    name: "${device_name} light"
