substitutions:
  device_name: fermax-veo
  logger_baud_rate: "0"
  wifi_output_power: "8.5"
  wifi_priority: "0.0"
  wifi_priority_aux: "100.0"
  wifi_signal_max: "-15.0"

esphome:
  name: ${device_name}
  platformio_options:
    board_build.f_cpu: 80000000L

esp32:
  board: lolin_c3_mini
  variant: esp32c3

packages:
  common: !include .common.yaml

### Config ###

binary_sensor:
  - platform: analog_threshold
    name: "${device_name} Intercom"
    sensor_id: adc3
    threshold: 2.4
    filters:
      - delayed_off: 3s

button:
  - platform: output
    name: "${device_name} Open"
    output: output_open
    duration: 100ms

output:
  - platform: gpio
    pin: GPIO4
    id: output_open

sensor:
  - platform: internal_temperature
    name: "${device_name} SoC Temperature"
    update_interval: 60s

  - platform: adc
    name: "${device_name} ADC"
    id: adc3
    update_interval: 0ms
    accuracy_decimals: 2
    pin: GPIO3
    attenuation: 12db
    filters:
      - multiply: 3.2
      - delta: 0.1

status_led:
  pin:
    number: GPIO7
