substitutions:
  device_name: "magichome-5ch"
  wifi_signal_max: "-40.0"

esphome:
  name: ${device_name}
  platformio_options:
    board_build.f_cpu: 80000000L

esp8266:
  board: esp8285
  restore_from_flash: false

wifi:
  domain: ".lan"
  output_power: 20
  reboot_timeout: 60min
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass
  networks:
    - ssid: !secret wifi_aux_ssid
      password: !secret wifi_aux_pass
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass

captive_portal:

logger:
  baud_rate: 0

api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

binary_sensor:
  - platform: gpio
    name: "${device_name} Button"
    id: button1
    pin:
      number: GPIO0
      inverted: true

button:
  - platform: restart
    name: "${device_name} Restart"

status_led:
  pin:
    number: GPIO2
    inverted: true

light:
  - platform: partition
    name: "${device_name} LEDs"
    segments:
      - single_light_id: led1
      - single_light_id: led2

  - platform: monochromatic
    name: "${device_name} LED 1"
    id: led1
    output: green_channel
    icon: mdi:led-strip
    effects:
      - pulse:
          name: "Default Pulse"
      - pulse:
          name: "Slow Pulse"
          transition_length: 3s
          update_interval: 3s
      - strobe:
          name: "Default Strobe"

  - platform: monochromatic
    name: "${device_name} LED 2"
    id: led2
    output: blue_channel
    icon: mdi:led-strip
    effects:
      - pulse:
          name: "Default Pulse"
      - pulse:
          name: "Slow Pulse"
          transition_length: 3s
          update_interval: 3s
      - strobe:
          name: "Default Strobe"

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO14
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: cold_white_channel
    pin: GPIO5
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: warm_white_channel
    pin: GPIO15
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true

sensor:
  - platform: uptime
    name: "${device_name} Uptime Timestamp"
    type: timestamp

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
    filters:
      - lambda: |-
          if (x <= ${wifi_signal_max}) {
            return x;
          } else {
            return {};
          }

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Madrid"
    servers:
      - 192.168.1.1
      - hora.rediris.es
      - es.pool.ntp.org
