substitutions:
  device_name: "magichome-5ch"
  logger_baud_rate: "0"
  wifi_output_power: "20"
  wifi_priority: "0"
  wifi_priority_aux: "0"
  wifi_signal_max: "-40.0"

esphome:
  name: ${device_name}
  platformio_options:
    board_build.f_cpu: 80000000L

esp8266:
  board: esp8285
  restore_from_flash: false

packages:
  common: !include .common.yaml

### Config ###

binary_sensor:
  - platform: gpio
    name: "${device_name} Button"
    id: button1
    pin:
      number: GPIO0
      inverted: true

light:
  - platform: partition
    name: "${device_name} LEDs"
    segments:
      - single_light_id: led1
      - single_light_id: led2

  - platform: monochromatic
    name: "${device_name} LED 1"
    id: led1
    output: green_channel
    icon: mdi:led-strip
    effects:
      - pulse:
          name: "Default Pulse"
      - pulse:
          name: "Slow Pulse"
          transition_length: 3s
          update_interval: 3s
      - strobe:
          name: "Default Strobe"

  - platform: monochromatic
    name: "${device_name} LED 2"
    id: led2
    output: blue_channel
    icon: mdi:led-strip
    effects:
      - pulse:
          name: "Default Pulse"
      - pulse:
          name: "Slow Pulse"
          transition_length: 3s
          update_interval: 3s
      - strobe:
          name: "Default Strobe"

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO14
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: cold_white_channel
    pin: GPIO5
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true
  - platform: esp8266_pwm
    id: warm_white_channel
    pin: GPIO15
    min_power: 0.07
    max_power: 0.68
    zero_means_zero: true

status_led:
  pin:
    number: GPIO2
    inverted: true
