substitutions:
  device_name: nodemcu-32s

esphome:
  name: ${device_name}

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: ".lan"
  reboot_timeout: 60min
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass

captive_portal:

logger:
  baud_rate: 0

api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

button:
  - platform: restart
    name: "${device_name} Restart"

sensor:
  - platform: uptime
    name: "${device_name} Uptime Timestamp"
    type: timestamp

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

  - platform: internal_temperature
    name: "${device_name} SoC Temperature"
    update_interval: 60s

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Madrid"
    servers:
      - 192.168.1.1
      - hora.rediris.es
      - es.pool.ntp.org
