substitutions:
  device_name: nodemcu32s

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: ".lan"
  ap:
    ssid: "Nodemcu-32S"
    password: !secret wifi_ap_pass

captive_portal:

logger:
  baud_rate: 0

api:
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:A9:4E'
    temperature:
      name: "Xiaomi MiFlora Temperatura"
    moisture:
      name: "Xiaomi MiFlora Humedad"
    illuminance:
      name: "Xiaomi MiFlora Iluminación"
    conductivity:
      name: "Xiaomi MiFlora Conductividad"

  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 300s
