substitutions:
  device_name: wemos_d1_mini

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: ".lan"
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_pass

captive_portal:

logger:

api:
  password: !secret api_pass

ota:
  password: !secret api_pass

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_pass

status_led:
  pin:
    number: GPIO2
    inverted: true

sensor:
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 300s